# Generated by Django 3.1.7 on 2023-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
